name: hello_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #latest version
  dio: 2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.0+6
  photo_view: ^0.2.2
  video_player: ^0.10.0+2
  shared_preferences: ^0.5.1+2
  multi_image_picker: ^4.1.2
  file_picker: ^1.3.3
  # photo: ^0.3.3
  flutter_spinkit: "^3.1.0"
  cached_network_image: ^0.7.0
  flutter_image_compress: ^0.2.4
  web_socket_channel: ^1.0.12
  sqflite: ^1.1.3
  flutter_local_notifications: ^0.6.0
  agora_rtc_engine: ^0.9.4
  fluttertoast: ^3.0.3
  audioplayers: ^0.11.0
  # flutter_generic_oauth: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - assets/images/login_bg.jpg
   - assets/images/video_default.jpg
   - assets/images/no_image.jpeg
   - assets/images/no_avatar.jpeg
  #  - assets/images/blog_icon.png
   - assets/images/chat_bg.jpeg
   - assets/images/text_bg_rtl.jpeg
   - assets/images/text_bg_ltr.jpeg
   - assets/images/launch.jpeg
   - assets/call.mp3

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
